In [169]:
import random
import numpy as np
    import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split


In [170]:
l =[]

f =[[],[],[]]


In [171]:
for i in range(1000):
    x1=random.randint(0,100)
    f[0].append(x1)
    
    x2=random.randint(0,100)
    f[1].append(x2)    
    
    x3=random.randint(0,100)
    f[2].append(x3)   
    
    y=5*x1+3*x2+1.5*x3+6
    l.append(y)

In [172]:
data={'f1':f[0],'f2':f[1],'f3':f[2],'label':l}

In [173]:
df = pd.DataFrame(data)

In [174]:
print(df)

     f1   f2   f3   label
0    78   84  111   814.5
1    84  159   61   994.5
2    53  109   66   697.0
3    11  177  124   778.0
4    96   65  181   952.5
..   ..  ...  ...     ...
995   3  117   48   444.0
996  87  161  119  1102.5
997  50   57  247   797.5
998  18  134   98   645.0
999   9   98  175   607.5

[1000 rows x 4 columns]


In [175]:
####rescaling

In [176]:
df=(df - df.mean())/df.std()
print(df)

           f1        f2        f3     label
0    0.979129 -0.275024 -0.431101  0.146009
1    1.187263  1.033949 -1.004282  0.847842
2    0.111906  0.161300 -0.946964 -0.312133
3   -1.345028  1.348103 -0.282074  0.003692
4    1.603529 -0.606631  0.371352  0.684081
..        ...       ...       ...       ...
995 -1.622539  0.300924 -1.153309 -1.298599
996  1.291329  1.068855 -0.339392  1.268942
997  0.007840 -0.746254  1.127951  0.079724
998 -1.102205  0.597625 -0.580128 -0.514885
999 -1.414405 -0.030682  0.302571 -0.661100

[1000 rows x 4 columns]


In [177]:
###train and test

In [178]:
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,:-1], l, test_size=0.4, random_state=42)
m = len(X_train)

In [179]:
###adding anew colwn called ones before the data

In [180]:
df.insert(0,'ones',1)


In [198]:
df

ones        f1        f2        f3     label
0       1  0.979129 -0.275024 -0.431101  0.146009
1       1  1.187263  1.033949 -1.004282  0.847842
2       1  0.111906  0.161300 -0.946964 -0.312133
3       1 -1.345028  1.348103 -0.282074  0.003692
4       1  1.603529 -0.606631  0.371352  0.684081
..    ...       ...       ...       ...       ...
995     1 -1.622539  0.300924 -1.153309 -1.298599
996     1  1.291329  1.068855 -0.339392  1.268942
997     1  0.007840 -0.746254  1.127951  0.079724
998     1 -1.102205  0.597625 -0.580128 -0.514885
999     1 -1.414405 -0.030682  0.302571 -0.661100

[1000 rows x 5 columns]

In [181]:
##separate x training data from y target variable

In [182]:
cols=df.shape[1]
x=df.iloc[:,0:cols-1]
y=df.iloc[:,cols-1:cols]

In [200]:

print('x data=\n',x)
print('y data=\n',y)


x data=
 [[ 1.          0.97912909 -0.27502404 -0.43110087]
 [ 1.          1.18726253  1.03394937 -1.00428184]
 [ 1.          0.11190641  0.16130043 -0.94696375]
 ...
 [ 1.          0.00783969 -0.74625447  1.12795137]
 [ 1.         -1.10220533  0.5976249  -0.58012793]
 [ 1.         -1.41440549 -0.03068234  0.30257077]]
y data=
 [[ 1.46008668e-01]
 [ 8.47842196e-01]
 [-3.12132664e-01]
 [ 3.69242418e-03]
 [ 6.84081040e-01]
 [ 9.53206904e-02]
 [-1.27130515e+00]
 [ 1.20664679e-01]
 [ 4.59884218e-01]
 [-2.51696999e-01]
 [-1.75665033e-01]
 [ 1.26504324e+00]
 [-1.78598307e+00]
 [-2.15618856e-03]
 [-5.73370699e-01]
 [-2.30650961e+00]
 [-1.99059484e-01]
 [ 6.02290140e-02]
 [-8.98853797e-02]
 [ 1.64130399e+00]
 [-1.03151203e+00]
 [ 1.26114416e+00]
 [-8.01466596e-01]
 [ 3.83852252e-01]
 [-3.39426190e-01]
 [-1.54220120e-01]
 [ 1.10128208e+00]
 [ 1.57705893e-01]
 [-9.35984689e-01]
 [ 1.61985908e+00]
 [ 6.87980115e-01]
 [-9.22337926e-01]
 [-1.64951544e+00]
 [-4.69955529e-02]
 [ 6.31443525e-01]
 [-7.

In [184]:
##convert from data frames to numpy matrices


In [185]:
x=np.matrix(x.values)
y=np.matrix(y.values)
theta=np.matrix(np.array([0,0,0,0]))

In [201]:
print('x \n',x)
print('x.shape= ',x.shape)
print('theta \n',theta)
print('theta.shape= ',theta.shape)
print('y \n',y)
print('y.shape= ',y.shape)

x 
 [[ 1.          0.97912909 -0.27502404 -0.43110087]
 [ 1.          1.18726253  1.03394937 -1.00428184]
 [ 1.          0.11190641  0.16130043 -0.94696375]
 ...
 [ 1.          0.00783969 -0.74625447  1.12795137]
 [ 1.         -1.10220533  0.5976249  -0.58012793]
 [ 1.         -1.41440549 -0.03068234  0.30257077]]
x.shape=  (1000, 4)
theta 
 [[0 0 0 0]]
theta.shape=  (1, 4)
y 
 [[ 1.46008668e-01]
 [ 8.47842196e-01]
 [-3.12132664e-01]
 [ 3.69242418e-03]
 [ 6.84081040e-01]
 [ 9.53206904e-02]
 [-1.27130515e+00]
 [ 1.20664679e-01]
 [ 4.59884218e-01]
 [-2.51696999e-01]
 [-1.75665033e-01]
 [ 1.26504324e+00]
 [-1.78598307e+00]
 [-2.15618856e-03]
 [-5.73370699e-01]
 [-2.30650961e+00]
 [-1.99059484e-01]
 [ 6.02290140e-02]
 [-8.98853797e-02]
 [ 1.64130399e+00]
 [-1.03151203e+00]
 [ 1.26114416e+00]
 [-8.01466596e-01]
 [ 3.83852252e-01]
 [-3.39426190e-01]
 [-1.54220120e-01]
 [ 1.10128208e+00]
 [ 1.57705893e-01]
 [-9.35984689e-01]
 [ 1.61985908e+00]
 [ 6.87980115e-01]
 [-9.22337926e-01]
 [-1.649515

In [187]:
#cost function in regression consider the Accuracy

In [188]:
def computCost(x,y,theta):
    z=np.power(((x*theta.T)-y),2)
    return np.sum(z)/(2*len(x))

In [189]:
print('Accuracy = ',computCost(x,y,theta))

Accuracy =  0.4994999999999999


In [190]:
#calc Grident Decent to calc the final weights

In [191]:
def gradientDesent(x,y,theta,alpha,iters):
    temp=np.matrix(np.zeros(theta.shape))
    parameters=int(theta.ravel().shape[1])
    cost=np.zeros(iters)
    
    for i in range(iters):
        error= (x*theta.T)-y
        for j in range(parameters):
            term=np.multiply(error,x[:,j])
            term[0,j]=theta[0,j]-((alpha/len(x))*np.sum(term))
            theta=temp
            cost[i]=computCost(x,y,theta)
            return theta,cost
        

    

In [192]:
alpha=0.01
iters=190000

In [193]:

g,cost=gradientDesent(x,y,theta,alpha,iters)

In [194]:
print('the final weights = \n',g)

the final weights = 
 [[0. 0. 0. 0.]]


In [195]:
print('cost= ',cost)

cost=  [0.4995 0.     0.     ... 0.     0.     0.    ]


In [197]:
print('computeCost=',computCost(x,y,g))

computeCost= 0.4994999999999999
