In [48]:
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [49]:
df = pd.read_csv('USA_Housing.csv')

In [50]:
df

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          79545.45857             5.682861                   7.009188   
1          79248.64245             6.002900                   6.730821   
2          61287.06718             5.865890                   8.512727   
3          63345.24005             7.188236                   5.586729   
4          59982.19723             5.040555                   7.839388   
...                ...                  ...                        ...   
4995       60567.94414             7.830362                   6.137356   
4996       78491.27543             6.999135                   6.576763   
4997       63390.68689             7.250591                   4.805081   
4998       68001.33124             5.534388                   7.130144   
4999       65510.58180             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09      23086.80050  1.059034e+06   
1                             3.09      40173.07217  1.505891e+06   
2                             5.13      36882.15940  1.058988e+06   
3                             3.26      34310.24283  1.260617e+06   
4                             4.23      26354.10947  6.309435e+05   
...                            ...              ...           ...   
4995                          3.46      22837.36103  1.060194e+06   
4996                          4.02      25616.11549  1.482618e+06   
4997                          2.13      33266.14549  1.030730e+06   
4998                          5.44      42625.62016  1.198657e+06   
4999                          4.07      46501.28380  1.298950e+06   

                                                Address  
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1     188 Johnson Views Suite 079\nLake Kathleen, CA...  
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                             USS Barnett\nFPO AP 44820  
4                            USNS Raymond\nFPO AE 09386  
...                                                 ...  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...  

[5000 rows x 7 columns]

In [51]:
df.drop(columns=['Address'], inplace = True)

In [52]:
df

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          79545.45857             5.682861                   7.009188   
1          79248.64245             6.002900                   6.730821   
2          61287.06718             5.865890                   8.512727   
3          63345.24005             7.188236                   5.586729   
4          59982.19723             5.040555                   7.839388   
...                ...                  ...                        ...   
4995       60567.94414             7.830362                   6.137356   
4996       78491.27543             6.999135                   6.576763   
4997       63390.68689             7.250591                   4.805081   
4998       68001.33124             5.534388                   7.130144   
4999       65510.58180             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  
0                             4.09      23086.80050  1.059034e+06  
1                             3.09      40173.07217  1.505891e+06  
2                             5.13      36882.15940  1.058988e+06  
3                             3.26      34310.24283  1.260617e+06  
4                             4.23      26354.10947  6.309435e+05  
...                            ...              ...           ...  
4995                          3.46      22837.36103  1.060194e+06  
4996                          4.02      25616.11549  1.482618e+06  
4997                          2.13      33266.14549  1.030730e+06  
4998                          5.44      42625.62016  1.198657e+06  
4999                          4.07      46501.28380  1.298950e+06  

[5000 rows x 6 columns]

In [53]:
####rescaling

In [54]:
df=(df - df.mean())/df.std()
print(df)

      Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0             1.028557            -0.296897                   0.021272   
1             1.000708             0.025899                  -0.255481   
2            -0.684561            -0.112292                   1.516092   
3            -0.491450             1.221450                  -1.392938   
4            -0.806992            -0.944739                   0.846657   
...                ...                  ...                        ...   
4995         -0.752033             1.869110                  -0.845504   
4996          0.929647             1.030719                  -0.408645   
4997         -0.487186             1.284342                  -2.170052   
4998         -0.054586            -0.446650                   0.141526   
4999         -0.288284             0.015213                  -0.194322   

      Avg. Area Number of Bedrooms  Area Population     Price  
0                         0.088053        -1.31

In [55]:
###adding anew colwn called ones before the data

In [56]:
df.insert(0,'ones',1)

In [57]:
df

ones  Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0        1          1.028557            -0.296897                   0.021272   
1        1          1.000708             0.025899                  -0.255481   
2        1         -0.684561            -0.112292                   1.516092   
3        1         -0.491450             1.221450                  -1.392938   
4        1         -0.806992            -0.944739                   0.846657   
...    ...               ...                  ...                        ...   
4995     1         -0.752033             1.869110                  -0.845504   
4996     1          0.929647             1.030719                  -0.408645   
4997     1         -0.487186             1.284342                  -2.170052   
4998     1         -0.054586            -0.446650                   0.141526   
4999     1         -0.288284             0.015213                  -0.194322   

      Avg. Area Number of Bedrooms  Area Population     Price  
0                         0.088053        -1.317467 -0.490032  
1                        -0.722229         0.403959  0.775431  
2                         0.930747         0.072403 -0.490162  
3                        -0.584481        -0.186716  0.080835  
4                         0.201493        -0.988289 -1.702348  
...                            ...              ...       ...  
4995                     -0.422425        -1.342598 -0.486747  
4996                      0.031334        -1.062641  0.709523  
4997                     -1.500101        -0.291907 -0.570187  
4998                      1.181935         0.651051 -0.094631  
4999                      0.071848         1.041520  0.189392  

[5000 rows x 7 columns]

In [58]:
##separate x training data from y target variable

In [59]:
cols=df.shape[1]
x=df.iloc[:,0:cols-1]
y=df.iloc[:,cols-1:cols]

In [60]:
print('x data=\n',x)
print('y data=\n',y)


x data=
       ones  Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0        1          1.028557            -0.296897                   0.021272   
1        1          1.000708             0.025899                  -0.255481   
2        1         -0.684561            -0.112292                   1.516092   
3        1         -0.491450             1.221450                  -1.392938   
4        1         -0.806992            -0.944739                   0.846657   
...    ...               ...                  ...                        ...   
4995     1         -0.752033             1.869110                  -0.845504   
4996     1          0.929647             1.030719                  -0.408645   
4997     1         -0.487186             1.284342                  -2.170052   
4998     1         -0.054586            -0.446650                   0.141526   
4999     1         -0.288284             0.015213                  -0.194322   

      Avg. Area Number of Bedr

In [61]:
##convert from data frames to numpy matrices

In [62]:
x=np.matrix(x.values)
y=np.matrix(y.values)
theta=np.matrix(np.array([0,0,0,0,0,0]))

In [63]:
print('x \n',x)
print('x.shape= ',x.shape)
print('theta \n',theta)
print('theta.shape= ',theta.shape)
print('y \n',y)
print('y.shape= ',y.shape)

x 
 [[ 1.          1.02855682 -0.29689735  0.02127221  0.08805341 -1.31746691]
 [ 1.          1.00070766  0.02589905 -0.25548055 -0.72222922  0.40395904]
 [ 1.         -0.68456069 -0.11229159  1.51609186  0.93074736  0.07240265]
 ...
 [ 1.         -0.48718581  1.28434176 -2.17005245 -1.50010056 -0.29190738]
 [ 1.         -0.05458606 -0.44664971  0.14152646  1.18193498  0.65105097]
 [ 1.         -0.28828389  0.01521325 -0.19432222  0.07184776  1.04152047]]
x.shape=  (5000, 6)
theta 
 [[0 0 0 0 0 0]]
theta.shape=  (1, 6)
y 
 [[-0.49003245]
 [ 0.77543074]
 [-0.4901615 ]
 ...
 [-0.57018697]
 [-0.09463074]
 [ 0.18939249]]
y.shape=  (5000, 1)


In [64]:
#loss function 

In [65]:
def lossFunction(x,y,theta):
    z=np.power(((x*theta.T)-y),2)
    return np.sum(z)/(2*len(x))

In [66]:
print('lossFunction = ',lossFunction(x,y,theta))

lossFunction =  0.4998999999999993


In [67]:
#calc Grident Decent 

In [71]:
def gradientDesent(x,y,theta,alpha,iters):
    temp=np.matrix(np.zeros(theta.shape))
    parameters=int(theta.ravel().shape[1])
    cost=np.zeros(iters)
    
    for i in range(iters):
        error= (x*theta.T)-y
        for j in range(parameters):
            term=np.multiply(error,x[:,j])
            term[0,j]=theta[0,j]-((alpha/len(x))*np.sum(term))
            theta=temp
            cost[i]=lossFunction(x,y,theta)
            return theta,cost
        

In [72]:
alpha=0.01
iters=190000

In [73]:
g,cost=gradientDesent(x,y,theta,alpha,iters)

In [75]:
print('the thetas is = \n',g)

the thetas is = 
 [[0. 0. 0. 0. 0. 0.]]


In [76]:
print('cost= ',cost)

cost=  [0.4999 0.     0.     ... 0.     0.     0.    ]


In [78]:
print('lossFunction=',lossFunction(x,y,g))

lossFunction= 0.4998999999999993
